### ISSUE TITLE
Flashforge dreamerNX issues connecting

### ISSUE THREAD

**Issue by glimpsewearables** [Mrnt/OctoPrint-FlashForge#67]
Not able to connect. On RPI4 octopi
Have tried adding usb permissions through standard method of adding line to file.

Still get LIBUSB access error. 
I am able to recognize the dreamerNX as reflected below nd within dmesg
Attatching errors

`2021-02-28 04:34:49,433 - octoprint.util.comm - INFO - Serial detection: Trying port FlashForge Dreamer NX 3D Printer, port:1:3, baudrate 9600
2021-02-28 04:34:49,434 - octoprint.plugins.GPX - INFO - [a]
2021-02-28 04:34:49,434 - octoprint.plugins.GPX - INFO - [b]
2021-02-28 04:34:49,434 - octoprint.plugins.GPX - INFO - [left]
2021-02-28 04:34:49,435 - octoprint.plugins.GPX - INFO - [machine]
2021-02-28 04:34:49,435 - octoprint.plugins.GPX - INFO - [printer]
2021-02-28 04:34:49,435 - octoprint.plugins.GPX - INFO - build_progress=1
2021-02-28 04:34:49,435 - octoprint.plugins.GPX - INFO - ditto_printing=0
2021-02-28 04:34:49,435 - octoprint.plugins.GPX - INFO - gcode_flavor=reprap
2021-02-28 04:34:49,435 - octoprint.plugins.GPX - INFO - machine_type=r1
2021-02-28 04:34:49,436 - octoprint.plugins.GPX - INFO - recalculate_5d=0
2021-02-28 04:34:49,436 - octoprint.plugins.GPX - INFO - [right]
2021-02-28 04:34:49,436 - octoprint.plugins.GPX - INFO - [x]
2021-02-28 04:34:49,436 - octoprint.plugins.GPX - INFO - [y]
2021-02-28 04:34:49,436 - octoprint.plugins.GPX - INFO - [z]
2021-02-28 04:34:49,438 - octoprint.plugins.GPX - INFO - {'None': {}, 'a': {}, 'b': {}, 'left': {}, 'machine': {}, 'printer': {'build_progress': '1', 'ditto_printing': '0', 'gcode_flavor': 'reprap', 'machine_type': 'r1', 'recalculate_5d': '0'}, 'right': {}, 'x': {}, 'y': {}, 'z': {}}
2021-02-28 04:34:49,438 - octoprint.plugins.GPX - INFO - Connecting through x3g.
2021-02-28 04:34:49,439 - octoprint.plugins.GPX - INFO - GPXPrinter created, port: FlashForge Dreamer NX 3D Printer, port:1:3, baudrate: 9600
2021-02-28 04:34:49,441 - octoprint.plugins.GPX - INFO - gpx.connect raised exception = [Errno 2] No such file or directory: 'FlashForge Dreamer NX 3D Printer, port:1:3'
2021-02-28 04:34:49,441 - octoprint.plugins.GPX - INFO - Failed to connect to x3g e = [Errno 2] No such file or directory: 'FlashForge Dreamer NX 3D Printer, port:1:3'.
2021-02-28 04:34:49,442 - octoprint.util.comm - ERROR - Unexpected error while connecting to serial port FlashForge Dreamer NX 3D Printer, port:1:3, baudrate 9600 from hook GPX: FileNotFoundError: '[Errno 2] No such file or directory: 'FlashForge Dreamer NX 3D Printer, port:1:3'' @ comm.py:_open_serial:3670
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/comm.py", line 3670, in _open_serial
    settings().getFloat(["serial", "timeout", "connection"]),
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/__init__.py", line 1890, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_GPX/__init__.py", line 130, in serial_factory
    self.printer = GpxPrinter(self, port, baudrate, timeout)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_GPX/gpxprinter.py", line 46, in __init__
    self._settings.get_boolean(["verbose"])))
FileNotFoundError: [Errno 2] No such file or directory: 'FlashForge Dreamer NX 3D Printer, port:1:3'
2021-02-28 04:34:49,443 - octoprint.util.comm - INFO - Serial detection: Could not open port FlashForge Dreamer NX 3D Printer, port:1:3, baudrate 9600, skipping
2021-02-28 04:34:49,444 - octoprint.util.comm - INFO - Changing monitoring state from "Detecting serial connection" to "Error: No more candidates to test, and no working port/baudrate combination detected."
2021-02-28 04:34:49,445 - octoprint.util.comm - INFO - Changing monitoring state from "Error: No more candidates to test, and no working port/baudrate combination detected." to "Offline (Error: No more candidates to test, and no working port/baudrate combination detected.)"
2021-02-28 04:34:49,477 - octoprint.plugins.action_command_notification - INFO - Notifications cleared
2021-02-28 04:34:49,539 - octoprint.plugins.flashforge - DEBUG - detect_printer()
2021-02-28 04:34:49,540 - octoprint.plugins.flashforge - DEBUG - Unable to get device name LIBUSB_ERROR_ACCESS [-3]
2021-02-28 04:34:49,540 - octoprint.plugins.flashforge - DEBUG - Found device 'unknown device' with Vendor ID: 0X1D6B, USB ID: 0X0003
2021-02-28 04:34:49,544 - octoprint.plugins.flashforge - DEBUG - Found device 'FlashForge Dreamer NX 3D Printer' with Vendor ID: 0X2B71, USB ID: 0X000A
2021-02-28 04:34:49,544 - octoprint.plugins.flashforge - INFO - Found a FlashForge FlashForge Dreamer NX 3D Printer, port:1:3
2021-02-28 04:34:49,545 - octoprint.plugins.flashforge - DEBUG - Unable to get device name LIBUSB_ERROR_ACCESS [-3]
2021-02-28 04:34:49,545 - octoprint.plugins.flashforge - DEBUG - Found device 'unknown device' with Vendor ID: 0X2109, USB ID: 0X3431
2021-02-28 04:34:49,546 - octoprint.plugins.flashforge - DEBUG - Unable to get device name LIBUSB_ERROR_ACCESS [-3]
2021-02-28 04:34:49,547 - octoprint.plugins.flashforge - DEBUG - Found device 'unknown device' with Vendor ID: 0X1D6B, USB ID: 0X0002
2021-02-28 04:34:49,978 - octoprint.plugins.tracking - INFO - Sent tracking event commerror_autodetect, payload: {'commerror_text': 'No more candidates to test, and no working port/baudrate combination detected.'}
2021-02-28 04:37:33,259 - octoprint.plugins.GPX - INFO - [a]
2021-02-28 04:37:33,259 - octoprint.plugins.GPX - INFO - [b]
2021-02-28 04:37:33,259 - octoprint.plugins.GPX - INFO - [left]
2021-02-28 04:37:33,259 - octoprint.plugins.GPX - INFO - [machine]
2021-02-28 04:37:33,260 - octoprint.plugins.GPX - INFO - [printer]
2021-02-28 04:37:33,260 - octoprint.plugins.GPX - INFO - build_progress=1
2021-02-28 04:37:33,260 - octoprint.plugins.GPX - INFO - ditto_printing=0
2021-02-28 04:37:33,260 - octoprint.plugins.GPX - INFO - gcode_flavor=reprap
2021-02-28 04:37:33,260 - octoprint.plugins.GPX - INFO - machine_type=r1
2021-02-28 04:37:33,260 - octoprint.plugins.GPX - INFO - recalculate_5d=0
2021-02-28 04:37:33,260 - octoprint.plugins.GPX - INFO - [right]
2021-02-28 04:37:33,260 - octoprint.plugins.GPX - INFO - [x]
2021-02-28 04:37:33,261 - octoprint.plugins.GPX - INFO - [y]
2021-02-28 04:37:33,261 - octoprint.plugins.GPX - INFO - [z]
2021-02-28 04:37:33,264 - octoprint.plugins.GPX - INFO - {'None': {}, 'a': {}, 'b': {}, 'left': {}, 'machine': {}, 'printer': {'build_progress': '1', 'ditto_printing': '0', 'gcode_flavor': 'reprap', 'machine_type': 'r1', 'recalculate_5d': '0'}, 'right': {}, 'x': {}, 'y': {}, 'z': {}}
`

**Comment by KeltE** [comment]
Are you using a GPX plugin? Dreamer NX does not work with GPX plugin. Search for the Flashforge plugin.
